version: '2'
services:
  app:
    build: .
    command: ruby coinbot.rb
    environment:
      MYSQL_HOST: mysql_host
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coinbot
      MYSQL_USER: coinbot
      MYSQL_PASSWORD: coinbot
      MYSQL_ENCODING: utf8
      TZ: 'Asia/Tokyo'
    depends_on:
      - db
    volumes:
      - .:/coinbot
  db:
    image: mysql:5.7
    container_name: mysql_host
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
